[env:freenove_esp32s3]
platform = espressif32@6.10.0
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem5AE70815351
monitor_port = /dev/cu.usbmodem5AE70815351
build_flags =
    -DARDUINO_USB_MODE=0
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Iinclude
board_build.arduino.memory_type = qio_opi

; build_src_filter = +<*> +<../include/g_model_int8_data.cpp> 
; build_src_filter = +<*> +<../include/MobileNetV1_a025.cpp> 
build_src_filter = +<*> +<../include/MobileNetV2_a035.cpp> 
lib_deps =
    esp32-camera
    johnosbb/MicroTFLite
